services:
  postgres:
    image: postgres:16
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  task-pro:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./task-pro:/app